site_name: Documentos Renova
site_description: |
  Documentação técnica dos sistemas Renova.
copyright: Copyright &copy; 2024 - Renova Soluções em Tecnologia
repo_url: https://renova-ti.visualstudio.com/

# Pages
nav:
  - index.md
  - R-Inspection.md
  - api-index.md
  # sub menu
  - "CFC":
    - "Agendamento Digital" : "./cfc/agendamentodigital.md"
    - "Agendamento Online"  : "./cfc/agendamentoonline.md"
    - "Biometric Matcher"   : "./cfc/biometric.md"
    - "Financeiro"          : "./cfc/financeiro.md"
    - "Gestão"              : "./cfc/gestao.md" 
    - "Identidade"          : "./cfc/identidade.md"
    - "Tele Aula"           : "./cfc/teleaula.md"
    - "Validação Digital"   : "./cfc/validacaodigital.md"
  - "CBPM":
    - "CBPM - Campanhia Baiana de Pesquisa Mineral": "./cbpmapi/cbpm.md"
    - "Litoteca Virtual": "./cbpmapi/litoteca.md"
    - "R-Collector": "./cbpmapi/rcolector.md"
    - "Upload Service": "./cbpmapi/upload.md"
  - "ESCRITÓRIO DE PROJETOS":
    - "ESCRITÓRIO DE PROJETOS": "./escritorio/escritorio.md"
  - "MOTOR BIOMÉTRICO":
    - "MOTOR BIOMÉTRICO": "./motorb/motor.md"
  - "PROJETO POLÍCIA CIVIL":
    - "Consulta Fotograma": "./projetopc/consultafoto.md"
    - "R-Ged": "./projetopc/rged.md"
    - "R-CroppingAPI": "./projetopc/rcropping.md"
    - "R-Cropping Desktop": "./projetopc/rcroppingdesk.md"
    - "R-CroppingPoC": "./projetopc/rcroppingpoc.md"
    - "Route Biometric": "./projetopc/routebiometric.md"
    - "Route BiometricAPI": "./projetopc/routebiometrica.md"    
  - "R COLLECTOR" :
    - "Biometric Engine": "./rcollector/biometricengine.md"
    - "CNHSyncAPI": "./rcollector/cnhsyncapi.md"
    - "Diagrama(s)": "./rcollector/diagrama.md"
    - "Modelagem Banco de Dados": "./rcollector/modelagembda.md"
    - "R-collector": "./rcollector/rcolector.md"
    - "R-CollectorAPI": "./rcollector/rcolletorapi.md"
    - "R-Collector Mobile": "./rcollector/rcollectormobile.md"
    - "R-Collector Offiline": "./rcollector/rcollectorof.md"
    - "R-Collector Online": "./rcollector/rcollectoron.md"
    - "R-Collector Services": "./rcollector/rcollectorserv.md"
    - "R-Collector CNHSync": "./rcollector/rcollectorcnh.md"
    - "R-Collector WEB": "./rcollector/rcollectorweb.md"
  - "R-INSPECTION":
    - "Biometric Engine": "./rinspection/biometriceng.md"
    - "Documentação": "./rinspection/documentacao.md"
    - "Modelagem Banco de Dados": "./rinspection/modelagemdba.md"
    - "R-Inspection 2.0": "./rinspection/rinspection2.0.md"
    - "R-InspectionAPI": "./rinspection/rinspectionapi.md"
    - "R-InspectionAPP": "./rinspection/rinspectionapp.md"
    - "R-InspectionAPP 2.0": "./rinspection/rinspectionap2.0.md"
    - "R"
# Plugins
plugins:
  - swagger-ui-tag

# Config
theme:
  name: material
  logo: assets/main-logo.svg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/main-logo.svg

