site_name: Documentos Renova,
site_description: |
  Documentação técnica dos sistemas Renova.
copyright: Copyright &copy; 2024 - Renova Soluções em Tecnologia <img referrerpolicy="no-referrer-when-downgrade" src="https://static.scarf.sh/a.png?x-pxid=c9065f3a-a090-4243-8f69-145d5de7bfca" />

# Pages
nav:
  - index.md
  - R-Inspection.md
  - api-index.md

# Plugins
plugins:
  - external-markdown
  - render_swagger:
      allow_arbitrary_locations : true

# Config
theme:
  name: material
  logo: assets/main-logo.svg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/main-logo.svg

