site_name: Documentos Renova
site_description: |
  Documentação técnica dos sistemas Renova.
copyright: Copyright &copy; 2024 - Renova Soluções em Tecnologia

# Pages
nav:
  - index.md
  - R-Inspection.md
  - api-index.md
  # sub menu
  # - CFC: "cfc.md"
  - "CFC":
    - "Gestão": "cfc.md"
    - "Financeiro" : "financeiro.md"
    - "Identidade" : "styling-your-docs.md"
# Plugins
plugins:
  - swagger-ui-tag

# Config
theme:
  name: material
  logo: assets/main-logo.svg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/main-logo.svg

